language: objective-c
notifications:
  email:
    - paul4hough@gmail.com

install:
  - sudo apt-get -y update

before_script:
  - type python
  - python --version
  - env

script:
  - python setup.py test_unit
  - sudo python setup.py test_system

after_script:
  - puppet --version
